### ISSUE TITLE
Hobbs And Shaw

### ISSUE THREAD

**Issue by pifantastic** [alunny/r_fast_r_furious#6]
While production has not started, I think it would be valuable to begin planning for the eventuality of supporting the upcoming spin-off, _Hobbs and Shaw_.

> On October 23, 2017, Dwayne Johnson posted a video on Instagram which showed the finished script for the spin-off, titled Hobbs and Shaw. In February 2018, David Leitch entered talks to direct the film. In March 2018, it was reported that the film will start production in September 2018.

Should we consider spin-offs as canon?

**Comment by pifantastic** [comment]
The Rock has posted about this on Instagram: https://www.instagram.com/p/BaCMqRLF9ZQ/

**Comment by alunny** [comment]
according to imdb the correct title is `Hobbs And Shaw` rather than `Hobbs and Shaw`

**Comment by alunny** [comment]
I've pushed eef2db825f36d0162709a9eed338841125d06083 to the prerelease `ff/2019` branch.

I'll cut a `9.0` release on or around July 26 2019. Please test any code that depends on this before then on the prerelease branch.

Thanks for the report.

**Comment by lukekarrys** [comment]
IMDb now lists the title as [Fast & Furious Presents: Hobbs & Shaw](https://www.imdb.com/title/tt6806448/). Does it make sense to support the full title and `Hobbs & Shaw`?

**Comment by alunny** [comment]
Yeah the poster has `The Fast and Furious presents` too. I’m a little skeptical it’ll show the full thing on the opening credits though.

Would prefer strictness rather than accepting both forms, otherwise this project looks like a bit of a joke.

**Comment by pifantastic** [comment]
I agree, rigor is paramount
